### ISSUE TITLE
Task list of known issues

### ISSUE THREAD

**Issue by zDania4** [zDania4/blocklist#4]
### Known issues when using this blocklist:
(_BM = Brave Mobile, PC = Windows_)

- [ ] Fix border still showing inside ad placement on CoomerSU. (BM)
- [ ] Block `a href` to ad site inside ad placement on both CoomerParty and CoomerSU. (BM and PC)
- [ ] Make upload buttons work again on SC. (PC)
- [ ] Make Eporners video player work again on Brave mobile. (BM)
